name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: |
          composer config policy.advisories.block false
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute Tests
        run: vendor/bin/phpunit
